param(
    [string]$OutputPath = 'wiki-build'
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$WikiSource = Join-Path $Root 'wiki'
$Out = if ([System.IO.Path]::IsPathRooted($OutputPath)) { $OutputPath } else { Join-Path $Root $OutputPath }

if (-not (Test-Path -LiteralPath $WikiSource)) { throw "Missing wiki source directory: $WikiSource" }

if (Test-Path -LiteralPath $Out) { Remove-Item -LiteralPath $Out -Recurse -Force }
New-Item -ItemType Directory -Force -Path $Out | Out-Null
Copy-Item -Path (Join-Path $WikiSource '*') -Destination $Out -Recurse -Force

$Scripts = Get-ChildItem -Path $Root -Filter '*.ps1' -File | Sort-Object Name
$Rows = foreach ($Script in $Scripts) {
    $Text = Get-Content -Raw -Path $Script.FullName
    $FirstComment = ($Text -split "`r?`n" | Where-Object { $_ -match '^\s*#\s*.+' } | Select-Object -First 1)
    if ($FirstComment) { $Description = ($FirstComment -replace '^\s*#\s*','').Trim() } else { $Description = 'PowerShell helper script.' }
    '| `{0}` | {1} |' -f $Script.Name, ($Description -replace '\|','/')
}

$Generated = @()
$Generated += '# Script Reference'
$Generated += ''
$Generated += 'This page is generated by `tools/Build-Wiki.ps1` during the GitHub wiki sync workflow.'
$Generated += ''
$Generated += '| Script | Purpose |'
$Generated += '| --- | --- |'
$Generated += $Rows
$Generated += ''
$Generated += 'Remote-only rule: these scripts are loaded from the configured raw web URL and executed in memory. They should not be downloaded as `.ps1` files to client computers.'
Set-Content -Path (Join-Path $Out 'Script-Reference.md') -Value ($Generated -join [Environment]::NewLine) -Encoding UTF8

$MenuPath = Join-Path $Root 'menu.ps1'
$MenuText = Get-Content -Raw -Path $MenuPath
$Options = [regex]::Matches($MenuText, "Write-Host '\s*([0-9]+\)|0\))\s*([^']+)'") | ForEach-Object {
    '| `{0}` | {1} |' -f $_.Groups[1].Value, ($_.Groups[2].Value.Trim() -replace '\|','/')
}
$MenuPage = @()
$MenuPage += '# Menu Options'
$MenuPage += ''
$MenuPage += 'This page is generated from `menu.ps1` by `tools/Build-Wiki.ps1`.'
$MenuPage += ''
$MenuPage += '| Option | Action |'
$MenuPage += '| --- | --- |'
$MenuPage += $Options
Set-Content -Path (Join-Path $Out 'Menu-Options.md') -Value ($MenuPage -join [Environment]::NewLine) -Encoding UTF8

Write-Host "Wiki output built at $Out"
